### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by sunitakodali** [josmanperez/realmAlertSystem#1]
Hello,

I was trying to push the changes to my application, but I am getting the error as "push failed: no dependencies found in the archive".

Could you please let me know, if there is anything I am missing?

Thank you.

**Comment by josmanperez** [comment]
Hello @sunitakodali , sorry for the late reply. I've seen that you have closed this issue. it's already solved?

Please let me know if you have any additional questions or concerns regarding the details above.

Kind Regards,
Josman
